config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :recipes, only: [:show, :create, :new, :edit, :update] do
    # /publish é o caminho relativo, e colocando "on: :member" informamos que é um membro da rota pai, que também depende do id da receita.
    # Formato final da rota /recipes/:id/publish
    patch :publish, on: :member 
  end

  resources :recipe_types, only: [:create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  enum status: { draft: 0, published: 2 }
  
  belongs_to :recipe_type
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.published
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def new
    @recipe_type = RecipeType.new
  end

  def create
    # The form data come inside of params
    @recipe_type = RecipeType.new(name: params[:recipe_type][:name])

    if @recipe_type.save
      flash[:notice] = 'Recipe type registered successfully!'
      return redirect_to(new_recipe_type_path)
    end

    render :new
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    # The form data come inside of params
    @recipe = Recipe.new(
      name: params[:recipe][:name],
      recipe_type_id: params[:recipe][:recipe_type_id],
      cuisine: params[:recipe][:cuisine],
      ingredients: params[:recipe][:ingredients],
      cook_method: params[:recipe][:cook_method],
      cook_time: params[:recipe][:cook_time],
    )

    if @recipe.save
      return redirect_to recipe_path(@recipe.id)
    end

    render :new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    success = @recipe.update(
      name: params[:recipe][:name],
      recipe_type_id: params[:recipe][:recipe_type_id],
      cuisine: params[:recipe][:cuisine],
      ingredients: params[:recipe][:ingredients],
      cook_method: params[:recipe][:cook_method],
      cook_time: params[:recipe][:cook_time],
    )

    return redirect_to recipe_path(@recipe.id) if success

    render :edit
  end

  def publish
    recipe = Recipe.find(params[:id])
    recipe.published!
    redirect_to recipe_path(recipe.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Book Recipes Abner</h1>

<% @recipes.each do |recipe| %>
  
  <%= link_to recipe.name, recipe  %> <br />

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li>
          <%= link_to 'Home', root_path %>
        </li>
        <li>
          <%= link_to 'Register new recipe', new_recipe_path %>
        </li>
        <li>
          <%= link_to 'Register new recipe type', new_recipe_type_path %>
        </li>
      </ul>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/recipe_types/new.html.erb
<h1>Recipe Type Register</h1>


<% if flash[:notice] %>
  <div style="margin: 30px 0">
    <%= flash[:notice] %>
  </div>
<% end %>


<%# O method form_with cria uma instancia atrelando ao Model, e coloca dentro de uma variável escopada ao bloco %>
<%= form_with model: @recipe_type do | form | %>
  <div>
    <%= form.label 'Name' %>
    <%= form.text_field :name %> <%# Input do tipo TEXT e logo depois qual o attributo do model %>
  </div>

  <div>
    <%= form.submit 'Salvar' %> <%# Input do tipo SUBMIT e 'Salvar' é o nome que será exibido dentro %>
  </div>
<% end %>

app/views/recipes/_form.html.erb
<%# O method cria uma instancia atrelando ao Model, e coloca dentro de uma variável escopada ao bloco %>
<%= form_with model: @recipe do | form | %>
  <%= form.label 'Name' %>
  <%= form.text_field :name %> <%# Input do tipo TEXT e logo depois qual o attributo do model %>
  <br />
  
  <%= form.label 'Recipe Type' %>
  <%= form.collection_select :recipe_type_id, RecipeType.all, :id, :name %>

  <br />

  <%= form.label 'Cuisine' %>
  <%= form.text_field :cuisine %>
  <br />

  <%= form.label 'Ingredients' %>
  <%= form.text_area :ingredients %>
  <br />

  <%= form.label 'Cook Method' %>
  <%= form.text_field :cook_method %> <%# TEXTAREA e logo depois qual o attributo do model %>
  <br />

  <%= form.label 'Cook Time (min)' %>
  <%= form.number_field :cook_time %> <%# Input do tipo NUMBER e logo depois qual o attributo do model %>
  <br />

  <%= form.submit 'Salvar' %> <%# Input do tipo SUBMIT e 'Salvar' é o nome que será exibido dentro %>
<% end %>

app/views/recipes/edit.html.erb
<%= render partial: 'form', locals: { recipe: @recipe } %>

app/views/recipes/new.html.erb
<%# O method cria uma instancia atrelando ao Model, e coloca dentro de uma variável escopada ao bloco %>
<%= form_with model: @recipe do | form | %>
  <%= form.label 'Name' %>
  <%= form.text_field :name %> <%# Input do tipo TEXT e logo depois qual o attributo do model %>
  <br />
  
  <%= form.label 'Recipe Type' %>
  <%= form.collection_select :recipe_type_id, RecipeType.all, :id, :name %>

  <br />

  <%= form.label 'Cuisine' %>
  <%= form.text_field :cuisine %>
  <br />

  <%= form.label 'Ingredients' %>
  <%= form.text_area :ingredients %>
  <br />

  <%= form.label 'Cook Method' %>
  <%= form.text_field :cook_method %> <%# TEXTAREA e logo depois qual o attributo do model %>
  <br />

  <%= form.label 'Cook Time (min)' %>
  <%= form.number_field :cook_time %> <%# Input do tipo NUMBER e logo depois qual o attributo do model %>
  <br />

  <%= form.submit 'Salvar' %> <%# Input do tipo SUBMIT e 'Salvar' é o nome que será exibido dentro %>
<% end %>

app/views/recipes/show.html.erb
<h1>Info about recipe: <%= @recipe.name %> </h1>

<%= link_to 'Editar', edit_recipe_path %>

<dl>
  <dt>
    <strong>Name: </strong> <%= @recipe.name %>
  </dt>

  <dd>
    <strong>Recipe Type: </strong> <%= @recipe.recipe_type.name if @recipe.recipe_type %>
  </dd>

  <dd>
    <strong>Cuisine: </strong> <%= @recipe.cuisine || 'Não descrito'  %>
  </dd>

  <dd>
    <strong>Ingredients: </strong> <%= @recipe.ingredients || 'Não descrito' %>
  </dd>

  <dd>
    <strong>Cook method: </strong> <%= @recipe.cook_method || 'Não descrito'  %>
  </dd>

  <dd>
    <strong>Cook time: </strong> <%= @recipe.cook_time || 'Não descrito'  %>
  </dd>

  <dd>
    <strong>Status: </strong> <%= @recipe.status  %>
  </dd>

  <br />

  <%= button_to 'Publicar', publish_recipe_path, { method: 'patch' } %>
</dl>